# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

durationinforce <- function(time, surv) {
    .Call('stactuar_durationinforce', PACKAGE = 'stactuar', time, surv)
}

rcpp_hello <- function() {
    .Call('stactuar_rcpp_hello', PACKAGE = 'stactuar')
}

